### ISSUE TITLE
Multiple Clip Lists?

### ISSUE THREAD

**Issue by ShadowKyogre** [heruoxin/Clip-Stack#12]
As the title says, something like the custom folders in [Clipper for Android](https://play.google.com/store/apps/details?id=org.rojekti.clipper). While it is easy for me to search the list for random clippings, there are some clips that I reuse quite a bit, but need to be organized separately. A good example of something that'd be a pain to search through the list manually would be this bb code snippet that I use to split long blocks of quoted text:

```
[/quote]

[quote="personhere"]
```

**Comment by heruoxin** [comment]
Thank you!
Clipper is a very beautiful and great app. Actually I won't build Clip Stack if I found it early. :) 
But custom folders may be too hard to understand for some light users such as my mom. I'm considering a feature like "Starred" in Gmail.
