### ISSUE TITLE
English expression issue

### ISSUE THREAD

**Issue by krrr** [heruoxin/Clip-Stack#13]
While doing Japanese translation of this project I found some English expression is very strange.
There is a string named "pref_storage_summary_infinite" in strings.xml, and it is translated into "永久存储剪贴板。" in Chinese. The string's content is "Remember all clips.", which means "记住所有夹子" in Chinese. Do you actually mean "Save clipboard forever"?

PS. My ID is kcworms in V2EX, please remove it from Japanese translator list. Because that translation is not done by me and has serious quality problem.

**Comment by heruoxin** [comment]
囧，之前没注意到，稍等我马上改掉……
PS: 好的，我马上移除掉。当时在 V2EX 上看到说到翻译质量问题后我已暂停该版本的发布。所以包含目前的这份日语翻译的版本仅在局部测试状态，未大规模传播。
PPS: 前天重新拜托了 Sephinroth，他表示今天去借一个 Android 来翻译，所以之前规划的是等他的翻译到了之后就换掉的……
真是非常不好意思。

**Comment by krrr** [comment]
嗯，期待质量良好的翻译。另外顺便问一下，叫“clip_notification_single_text”的字符串我在操作APP的时候从来没遇到过，它是什么时候才会出现？我的设备是jelly bean

**Comment by heruoxin** [comment]
哦哦，那个在下一个版本中才会出现，位于通知的底部，不过高度还在调整中……

![screenshot](https://cloud.githubusercontent.com/assets/1999794/6440171/55454586-c115-11e4-825b-b07982494bbe.png)
