### ISSUE TITLE
Will 1.3.0 (available from play-store) be open-sourced, as well?

### ISSUE THREAD

**Issue by krt16s** [heruoxin/Clip-Stack#21]

**Comment by pejakm** [comment]
I'm interested in this, too.

**Comment by heruoxin** [comment]
Source code has updated.

**Comment by pejakm** [comment]
Thanks, @heruoxin. :)

**Comment by pejakm** [comment]
Again, 1.4 came out to Playstore, but there's no code on Github yet. Is there any real reason for this?

**Comment by pejakm** [comment]
@heruoxin ?
