### ISSUE TITLE
[Feature request] "Only notify when clipboard is not empty" option

### ISSUE THREAD

**Issue by stuartpb** [heruoxin/Clip-Stack#27]
I'd like Clip Stack's notifications to be like the "Connected" notifications that are pinned when a device is connected, reminding me that I currently have (potentially compromising) content on my clipboard, and that I can use Clip Stack to clear it.

**Comment by heruoxin** [comment]
Clip stack is a 'stack' for system clipboard. It will automatic resume the top clips in it to system clipboard after reboot. So the clipboard will never be empty unless you clear all clips.

**Comment by stuartpb** [comment]
Yes, that is what I want, the ability to clear the topmost item in the stack by dismissing the notification, thus bringing the next item in the stack (if any) to the clipboard.

**Comment by heruoxin** [comment]
I see... It's impossible to swipe only a part of notification on phone, but on wear it's possible. I'll try to add that on wear.

**Comment by stuartpb** [comment]
Sorry, I confused my last comment with #28 - I don't know what "swip[ing] only a part of [a] notification" would have to do with this one (which is only about not showing a notification when the clip stack is empty).

**Comment by stuartpb** [comment]
(https://github.com/heruoxin/Clip-Stack/issues/29#issuecomment-97509644 explained what swiping a part of a notification is about.)
